import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/commponents/navbar";
import LoaderWrapper from "@/commponents/loding";
import SidebarProvider from "@/context/bookscontext";
import PanelLayout from "./(group2)/panel/checing";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html >
      <body>
        <SidebarProvider>
        <LoaderWrapper>
        <PanelLayout />
        {children}
        </LoaderWrapper>
      </SidebarProvider>
      </body>
    </html>
  );
}
